import { CheckCheck, ShieldCheck } from 'lucide-react';
import { useEffect, useState } from 'react';
import api from '../api.js';
import { Badge, Empty, SectionTitle } from '../components/ui.jsx';

export default function IncidentLog() {
  const [incidents, setIncidents] = useState([]);
  const [filter, setFilter] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const load = () => {
    setError('');
    api.get('/incidents')
      .then(({ data }) => { setIncidents(data); setLoading(false); })
      .catch(() => {
        setError('Could not load the incident log. Is the backend running on :8001?');
        setLoading(false);
      });
  };

  useEffect(() => { load(); }, []);

  const patch = async (id, status) => {
    await api.patch(`/incidents/${id}`, { status });
    load();
  };

  const visible = filter ? incidents.filter((i) => i.severity === filter) : incidents;

  if (loading) return <div className="text-zinc-400">Loading incidents…</div>;
  if (error) {
    return (
      <div className="panel max-w-xl">
        <p className="text-sm text-red-400">{error}</p>
        <button className="btn-primary mt-4" onClick={load}>Retry</button>
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-6xl">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-extrabold">Safety Incident Log</h1>
          <p className="text-sm text-zinc-400">
            Every incident is generated by the deterministic rule engine — never by the AI model.
            Supervisors can acknowledge and resolve incidents here.
          </p>
        </div>
        <select className="input w-40" value={filter} onChange={(e) => setFilter(e.target.value)}>
          <option value="">All severities</option>
          {['CRITICAL', 'HIGH', 'WARNING'].map((s) => <option key={s}>{s}</option>)}
        </select>
      </div>

      {visible.length === 0 ? (
        <Empty text="No incidents logged. A clean safety record is the goal!" />
      ) : (
        <div>
          <SectionTitle title={`${visible.length} incident(s)`} />
          <div className="panel p-0 overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-xs uppercase text-zinc-400 border-b border-cat-line">
                  {['Time', 'Type', 'Severity', 'Operator', 'Description', 'Action taken', 'Status', ''].map((h) => (
                    <th key={h} className="px-4 py-2">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {visible.map((inc) => (
                  <tr key={inc.id} className="border-b border-cat-line/40 align-top">
                    <td className="px-4 py-2 text-xs text-zinc-400 whitespace-nowrap">
                      {inc.timestamp ? inc.timestamp.replace('T', ' ').slice(0, 16) : '—'}
                    </td>
                    <td className="px-4 py-2 font-semibold">{inc.incident_type}</td>
                    <td className="px-4 py-2"><Badge>{inc.severity}</Badge></td>
                    <td className="px-4 py-2 text-xs">{inc.operator_id}</td>
                    <td className="px-4 py-2 text-xs max-w-xs">{inc.description}</td>
                    <td className="px-4 py-2 text-xs max-w-xs">{inc.action_taken}</td>
                    <td className="px-4 py-2"><Badge>{inc.status}</Badge></td>
                    <td className="px-4 py-2 text-right whitespace-nowrap">
                      {inc.status === 'Open' && (
                        <button className="btn-ghost text-xs mr-2"
                          onClick={() => patch(inc.id, 'Acknowledged')}>
                          <CheckCheck size={13} /> Acknowledge
                        </button>
                      )}
                      {inc.status !== 'Resolved' && (
                        <button className="btn-primary text-xs"
                          onClick={() => patch(inc.id, 'Resolved')}>
                          <ShieldCheck size={13} /> Resolve
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
